apiVersion: v1
kind: Service
metadata:
  name: warehouse
  labels:
    app: warehouse
spec:
  selector:
    app: warehouse
  ports:
    - name: "http"
      port: 9020
      targetPort: 31100
  type: NodePort