server:
  port: 9020

spring:
  datasource:
    username: MT
    password: kjio0988
    url: jdbc:mysql://localhost:3306/offpayapdb1
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#    database-platform: org.hibernate.dialect.Oracle12cDialect